### PR TITLE
Add sign in with apple method upstream sync 2

### PR DESCRIPTION
**Pull request by kelkarajay**
👋 This pull request is to basically bring this branch up to date with django-allauth upstream.

## General

 - [ ] Make sure you use [semantic commit messages](https://seesparkbox.com/foundry/semantic_commit_messages).
       Examples: `"fix(google): Fixed foobar bug"`, `"feat(accounts): Added foobar feature"`.
 - [ ] All Python code must be 100% pep8 and isort clean.
 - [ ] JavaScript code should adhere to [StandardJS](https://standardjs.com).
 - [ ] If your changes are significant, please update `ChangeLog.rst`.
 - [ ] Feel free to add yourself to `AUTHORS`.
 
 ## Provider Specifics
 
 In case you add a new provider:
 
- [ ] Make sure unit tests are available.
- [ ] Add an entry of your provider in `test_settings.py::INSTALLED_APPS` and `docs/installation.rst::INSTALLED_APPS`.
- [ ] Add documentation to `docs/providers.rst`.
- [ ] Add an entry to the list of supported providers over at `docs/overview.rst`.

### CODE REVIEW

**Comment by kelkarajay** [comment]
@safwanrahman Done the rebase 🙂

**Comment by safwanrahman** [comment]
I think this can not be done without fast forward merge! 😞 It is hard to review this big change!

**Comment by safwanrahman** [comment]
@0leg5ergeev any thoughts to rebase PR with fast forward merge? I think you should do this instead of someone sending a PR. You should rebase and fix the conflicts and push to your branch again.

**Comment by kelkarajay** [comment]
^ or that. My main motive is to get it up to date so that [this](https://github.com/pennersr/django-allauth/pull/2424#issuecomment-685104398) can be done as @pennersr wrote.

**Comment by safwanrahman** [comment]
@kelkarajay Thanks for your effort. I am thinking the way to solve it in a easier way so it is possible to review the changes.

**Comment by safwanrahman** [comment]
I will rebase and will try to push it in my local branch.

**Comment by kelkarajay** [comment]
Closing this pull request since, Apple Sign in seems to be merged to master on `django-allauth`master and this one is no longer required.

**Pull request closed without merging**
